# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableWindow(object):
    def setupUi(self, TableWindow):
        TableWindow.setObjectName("TableWindow")
        TableWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TableWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnRead = QtWidgets.QPushButton(self.centralwidget)
        self.btnRead.setGeometry(QtCore.QRect(80, 430, 181, 101))
        self.btnRead.setObjectName("btnRead")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(310, 440, 171, 101))
        self.btnSave.setObjectName("btnSave")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(530, 440, 191, 101))
        self.btnClear.setObjectName("btnClear")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 10, 711, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        TableWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TableWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        TableWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TableWindow)
        self.statusbar.setObjectName("statusbar")
        TableWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TableWindow)
        QtCore.QMetaObject.connectSlotsByName(TableWindow)

    def retranslateUi(self, TableWindow):
        _translate = QtCore.QCoreApplication.translate
        TableWindow.setWindowTitle(_translate("TableWindow", "MainWindow"))
        self.btnRead.setText(_translate("TableWindow", "Считать данные"))
        self.btnSave.setText(_translate("TableWindow", "Сохранить"))
        self.btnClear.setText(_translate("TableWindow", "Очистить"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TableWindow", "Температура"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TableWindow", "Влажность"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TableWindow", "Освещение"))
